namespace Tests.Syntax.TestOnGherkinWithStringOnlyApi.CustomFramework;

public interface IDescribeTestInputAndRenderTestOutcomeWithStrings :
	IExecuteTheTestAndRenderItsOutcomeAsString,
	IExposeTestRunningExecutionPublicly,
	IBuildTestInputAndSystemUnderTestFromStringDescription
{
}
